// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/title-screen/Ember.tsx": () => import("../components/mockups/title-screen/Ember.tsx"),
  "./components/mockups/title-screen/Steel.tsx": () => import("../components/mockups/title-screen/Steel.tsx")
};
